# Generated by Django 4.2.7 on 2025-10-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simplifiedadoptionrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Solicitud Simplificada de Adopción', 'verbose_name_plural': 'Solicitudes de Adopción'},
        ),
    ]
