# Generated by Django 4.2.7 on 2025-10-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='friendly_with_kids',
            field=models.BooleanField(default=True, verbose_name='Amigable con niños'),
        ),
    ]
